name: link_up
description: "A new Flutter project for LinkUp Chat Web App."
publish_to: 'none' # Private project, not for pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Icons for iOS style
  cupertino_icons: ^1.0.8

  # Firebase dependencies
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add assets if needed
  # assets:
  #   - assets/images/

  # Add custom fonts if needed
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf